command: ['npm', 'run', 'start']
env:
  - name: npm_config_omit
    value: dev
  - name: LAKEBASE_ENDPOINT
    valueFrom: postgres
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_VOLUME_FILES
    value: /Volumes/main/default/flight_viz_cache
